/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Experience {
  'id' : bigint,
  'startYear' : bigint,
  'endYear' : [] | [bigint],
  'role' : string,
  'description' : string,
  'company' : string,
}
export interface Project {
  'id' : bigint,
  'url' : [] | [string],
  'title' : string,
  'description' : string,
  'techStack' : Array<string>,
}
export type Time = bigint;
export interface _SERVICE {
  'addExperience' : ActorMethod<
    [string, string, bigint, [] | [bigint], string],
    bigint
  >,
  'addProject' : ActorMethod<
    [string, string, Array<string>, [] | [string]],
    bigint
  >,
  'addSkill' : ActorMethod<[string], undefined>,
  'deleteExperience' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getAbout' : ActorMethod<[], { 'bio' : string, 'skills' : Array<string> }>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'removeSkill' : ActorMethod<[string], undefined>,
  'submitMessage' : ActorMethod<[string, string, string], bigint>,
  'updateBio' : ActorMethod<[string], undefined>,
  'updateExperience' : ActorMethod<
    [bigint, string, string, bigint, [] | [bigint], string],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, Array<string>, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];