/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Experience = IDL.Record({
  'id' : IDL.Nat,
  'startYear' : IDL.Nat,
  'endYear' : IDL.Opt(IDL.Nat),
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addExperience' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addSkill' : IDL.Func([IDL.Text], [], []),
  'deleteExperience' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAbout' : IDL.Func(
      [],
      [IDL.Record({ 'bio' : IDL.Text, 'skills' : IDL.Vec(IDL.Text) })],
      ['query'],
    ),
  'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'removeSkill' : IDL.Func([IDL.Text], [], []),
  'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateBio' : IDL.Func([IDL.Text], [], []),
  'updateExperience' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
      [],
      [],
    ),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Experience = IDL.Record({
    'id' : IDL.Nat,
    'startYear' : IDL.Nat,
    'endYear' : IDL.Opt(IDL.Nat),
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addExperience' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addSkill' : IDL.Func([IDL.Text], [], []),
    'deleteExperience' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAbout' : IDL.Func(
        [],
        [IDL.Record({ 'bio' : IDL.Text, 'skills' : IDL.Vec(IDL.Text) })],
        ['query'],
      ),
    'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'removeSkill' : IDL.Func([IDL.Text], [], []),
    'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateBio' : IDL.Func([IDL.Text], [], []),
    'updateExperience' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
        [],
        [],
      ),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };